### ISSUE TITLE
Description of filtering in the README.md file is the same as that of spatial

### ISSUE THREAD

**Issue by rjshaver** [mathnet/mathnet-filtering#11]
I was looking at the mathnet repos and saw that the description of filtering was the same as spatial.  However, it is different in the project website.  I made a correction and put through a pull request(or will shortly).

**Comment by cdrnet** [comment]
Yes, my bad. The pull request #12 has already been merged. Thanks a lot for fixing this!

**Comment by rjshaver** [comment]
Glad to help!  You are doing some great work.  I may never use it and may not understand it all, but I can tell by looking at the code I saw.  Keep up the great work.
