### ISSUE TITLE
Support .NET 3.5

### ISSUE THREAD

**Issue by aalmada** [mathnet/mathnet-filtering#3]
Please add support for .NET 3.5 (like in Numerics) as Unity 3D only supports this version of .NET
Thanks!

**Comment by cdrnet** [comment]
Is .Net 3.5 support still a requirement for Unity 3D these days?

**Comment by picklebread** [comment]
Unfortunately .Net 3.5 is still a requirement (though supposedly this will be upgraded some time soon?). Any update on the progress here?  I'd like to use this in Unity as well.

**Comment by cdrnet** [comment]
Math.NET Filtering - finally - supports .Net 3.5 (and portable profile 259), since v0.3.0.
