### ISSUE TITLE
Support Xamarin Android

### ISSUE THREAD

**Issue by avinabmalla** [mathnet/mathnet-filtering#6]
I was unable to add the NuGet package to a Xamarin Android project. It was strange, as I could add the numerics package but not this one. Mybe this project was created as a regular class library instead of a portable one.

![2016-07-22](https://cloud.githubusercontent.com/assets/6552000/17060146/66b8d56c-5048-11e6-9e81-eecd8a950d88.png)

Thanks!

**Comment by tura08** [comment]
I have created a portable class library for mathnet-filtering that passed the current unit tests and works in my application. Would the mathnet team be interested in a pull request for this?

**Comment by cdrnet** [comment]
I'd certainly accept a PR to add support for a PCL build. To keep it maintainable it should follow the same style than the other Math.NET projects do (mostly Numerics) though, e.g. such that the release process is fully automated.

**Comment by tura08** [comment]
Would you prefer a separate PCL project to be added to the current solution, or that the PCL replaces the current project?

**Comment by cdrnet** [comment]
I think i the medium term we'd want to target both .Net Framework (pure; v4 or higher) and .Net Standard v2.0. Until the tooling around .Net Standard is ready, having two projects, one for .Net 4 and one for a PCL would make sense, and is also in line with the other Math.NET Projects (e.g. Numerics: [PCL project files](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Numerics-Portable259.csproj), [.All solution including them](https://github.com/mathnet/mathnet-numerics/blob/master/MathNet.Numerics.All.sln#L60), , [build package](https://github.com/mathnet/mathnet-numerics/blob/master/build.fsx#L116), [build variants](https://github.com/mathnet/mathnet-numerics/blob/master/build.fsx#L459), etc)

**Comment by cdrnet** [comment]
(I'd propose to support only 1 PCL profile here, of course, not 5 different ones like Numerics)

**Comment by tura08** [comment]
Ok. So if I forked the master, added the PCL project to the solution and did a PR, would anything else need to change?

**Comment by cdrnet** [comment]
That would be fine - I can take care of the rest. Thanks!

**Comment by tura08** [comment]
Ok. I'll get on it.

**Comment by tura08** [comment]
PR has been submitted

**Comment by marcusturewicz** [comment]
@cdrnet How is the PR going?

**Comment by tura08** [comment]
@cdrnet How the PR going? Anything I can do to help?

**Comment by cdrnet** [comment]
Math.NET Filtering - finally - supports the portable profile 259 (and .Net 3.5), since v0.3.0.

@tura08 thanks a lot for putting work into this and providing a pull request. Unfortunately I was not clear enough what I meant with adding a project (this is a learning for me - I meant just the project file, pointing to the same sources) and I could therefore not merge the pull request as it would have deviated from the Math.NET approach, which would make this project unmaintainable for me.

**Comment by tura08** [comment]
@cdrnet not a problem, glad to help. Out of curiosity, what did you adjust in the project file to get it to build as PCL? I can't see anything in the latest commit.

**Comment by cdrnet** [comment]
@tura08 ah, forgot to push. It is [there](https://github.com/mathnet/mathnet-filtering/blob/master/src/Filtering/Filtering-Portable259.csproj) now.
